### ISSUE TITLE
README typo ?

### ISSUE THREAD

**Issue by eddelbuettel** [jart/json.cpp#4]
Should

> With gcc -O3 13.2 on Ubuntu 14.04

reference Ubuntu *24.04* instead of *14.04*?  

It is of course possible you ported gcc 13 back to 14.04 (from 2014) running on threadripper, but maybe not likely.

**Comment by jart** [comment]
Thanks for pointing this out!

**Comment by eddelbuettel** [comment]
Pleasure!  We have such tunnel vision -- I did not notice on 1st or 2nd visit but only I saw the screenshot (again) of my skeet about the repo.  If I had been surer I would have sent you a one-char PR but I figured "mebbe just mebbe" this meant to be.

Thanks for all the fine work you do.  Really appreciated.
