### ISSUE TITLE
About the json parsing performance.

### ISSUE THREAD

**Issue by zhengshuxin** [jart/json.cpp#6]
The nlohmann's library performance is too slowly, it needn't to compare with it. I've tested some other json libs that they are all more quickly than nlohmann. Below are test results:
[yyjson](https://github.com/ibireme/yyjson):  count=100000, cost=90.00 ms, speed=1111111.11, size=658.04 MB
[cjson](https://github.com/DaveGamble/cJSON): count=100000, cost=935.00 ms, speed=106951.87, size=63.34 MB
[rapidjson](https://github.com/Tencent/rapidjson): count=100000, cost=157.00 ms, speed=636942.68, size=377.22 MB
jtjson: count=100000, cost=976.00 ms, speed=102459.02, size=60.68 MB

The jtjson is jart/json.cpp which is some little slower than cjson.

**Comment by limingchina** [comment]
@zhengshuxin ,what does the cost mean? It has 'ms' unit. What the unit of the speed? Is the RAM peak consumption?

Maybe you can publish your benchmark code?

**Comment by zhengshuxin** [comment]
> @zhengshuxin ,what does the cost mean? It has 'ms' unit. What the unit of the speed? Is the RAM peak consumption?
> 
> Maybe you can publish your benchmark code?
The test result above means that parsing json 100000 times, the total time cost in milliseconds. And the codes is in https://github.com/acl-dev/demo/tree/master/benchmark/json .
